### ISSUE TITLE
"can't decode into non-slice invalid"

### ISSUE THREAD

**Issue by spxtr** [shurcooL/githubql#18] opened 2017-08-29 19:06 UTC
Of the two following queries, the first succeeds and the second spits up an error. I spent a while adding debug printfs in graphql/internal/jsonutil but I wasn't able to figure it out. All I know is that the `Commits` object in the second query causes the problem. Removing that object and replacing it with something else in the PR works fine.

Let me know if you need more info :)
```go
package main

import (
    "context"
    "fmt"
    "github.com/shurcooL/githubql"
    "golang.org/x/oauth2"
    "os"
)

type repoQuery struct {
    Repository struct {
        PullRequests struct {
            Nodes []struct {
                Commits struct {
                    Nodes []struct {
                        URL githubql.URI `graphql:"url"`
                    }
                } `graphql:"commits(last: 1)"`
            }
        } `graphql:"pullRequests(first: 1)"`
    } `graphql:"repository(owner: \"kubernetes\", name: \"test-infra\")"`
}

type searchQuery struct {
    Search struct {
        Nodes []struct {
            PullRequest struct {
                Commits struct {
                    Nodes []struct {
                        URL githubql.URI `graphql:"url"`
                    }
                } `graphql:"commits(last: 1)"`
            } `graphql:"... on PullRequest"`
        }
    } `graphql:"search(type: ISSUE, first: 1, query: \"type:pr repo:kubernetes/test-infra\")"`
}   

func main() {
    src := oauth2.StaticTokenSource(
        &oauth2.Token{AccessToken: os.Getenv("GITHUB_TOKEN")},
    )   
    httpClient := oauth2.NewClient(context.Background(), src)
    
    client := githubql.NewClient(httpClient)
    sq := searchQuery{}
    if err := client.Query(context.Background(), &sq, nil); err != nil {
        fmt.Printf("Search error: %v\n", err)
    }
    rq := repoQuery{}
    if err := client.Query(context.Background(), &rq, nil); err != nil {
        fmt.Printf("Repo error: %v\n", err)
    }
} 
```
```
$ GITHUB_TOKEN=<redacted> go run test.go
Search error: can't decode into non-slice invalid
```

**Comment by shurcooL** [comment] 2017-08-29 19:57
Thanks a lot for reporting this. I suspect this could be a bug in `jsonutil` on some particular edge case. That's where the error [comes from](https://github.com/shurcooL/graphql/blob/52ce28a2c9fdfbdb3377232422c7915fa04b678a/internal/jsonutil/graphql.go#L125).

Quick question, are you using the latest version of `githubql` (and its dependencies)? Or something older?

I will try to reproduce it, investigate it, and fix it if it's a bug on my side.

**Comment by spxtr** [comment] 2017-08-29 20:08
Thanks for the quick response. I'm using https://github.com/shurcooL/githubql/commit/b3091cd0b2f573f6945eb6f15b0559c06330a1a8 and https://github.com/shurcooL/graphql/commit/52ce28a2c9fdfbdb3377232422c7915fa04b678a.

**Comment by shurcooL** [comment] 2017-08-29 20:12
Thanks. I can reproduce with latest. Most likely it's a bug in `jsonutil`. I'll investigate and post updates.

**Comment by shurcooL** [comment] 2017-08-29 22:07
This was indeed a bug in `jsonutil`. It was not able to handle this query because there was a slice of nodes inside an inline fragment. I missed that edge case in #15. As I wrote [there](https://github.com/shurcooL/githubql/pull/15#issuecomment-313996792):

> This is a large and riskier-than-usual PR. It replaces the extremely well-tested `encoding/json` unmarshaler with a brand new that was implemented over the last few days for the custom needs of `graphql`: to unmarshal a JSON-encoded GraphQL server response into a query data structure. So there's a chance of edge cases that are not going to be handled.

That's what happened here.

This is now fixed in https://github.com/shurcooL/graphql/commit/68e5b1b3ab56633e42939506bc61f0b9fb2b7a79. I've also added a test so this won't regress.

You should see the problem go away after updating to the latest version:

```
go get -u github.com/shurcooL/githubql
```

(Or equivalent if you're using vendoring.)

Thank you very much @spxtr for reporting this bug and providing an easily reproducible test case!

**Closed** 2017-08-29 22:06 UTC
